# Generated by Django 2.2.1 on 2019-05-06 22:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.Loan",
                verbose_name="loan",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment",
            field=models.CharField(
                choices=[("made", "made"), ("missed", "missed")],
                default="missed",
                max_length=6,
                verbose_name="payment",
            ),
        ),
    ]
