# Generated by Django 2.2.1 on 2019-05-10 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("api", "0002_auto_20190506_1945")]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AddField(
            model_name="loan",
            name="updated",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="updated",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AddField(
            model_name="payment",
            name="updated",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="updated",
            ),
            preserve_default=False,
        ),
    ]
