# Generated by Django 2.2.1 on 2019-05-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20190510_2138"),
        ("api", "0003_auto_20190508_1423"),
    ]

    operations = []
