# Generated by Django 2.2.1 on 2019-05-12 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("api", "0004_merge_20190511_2115")]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now_add=True, verbose_name="updated"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("surname", models.CharField(max_length=255, verbose_name="surname")),
                ("email", models.EmailField(max_length=255, verbose_name="e-mail")),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telephone"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date of creation"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        verbose_name="natural persons register",
                    ),
                ),
            ],
            options={"verbose_name": "Customer", "verbose_name_plural": "Customers"},
        )
    ]
