# Generated by Django 2.2.1 on 2019-05-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0005_customer")]

    operations = [
        migrations.RenameModel(old_name="Customer", new_name="Client"),
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
    ]
