# Generated by Django 2.2.1 on 2019-05-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0006_auto_20190512_1834")]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="client",
            field=models.ForeignKey(
                default="1e4c777d-ec05-4b0b-b4be-10cb5a0d1e82",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.Client",
                verbose_name="client",
            ),
            preserve_default=False,
        )
    ]
