# Generated by Django 2.2.1 on 2019-05-17 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0007_loan_client")]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="amount"
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.Client",
                verbose_name="client_id",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="rate",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="rate"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="amount"
            ),
        ),
    ]
